### PR TITLE
Add drop in the comma, single quote and backquote

### PR DESCRIPTION
**Pull request by petrolifero**
Sorry about that.

### CODE REVIEW

**Comment by rain-1** [comment]
Thank you! Can you rebase this off the current HEAD though please?

I repaired the `unquot` problem!

**Comment by petrolifero** [comment]
As you has merged, want you yet to rebase? Because I cannot do this in your repository

**Comment by rain-1** [comment]
That was perfect! it is a pleasure working with you :D

**Comment by petrolifero** [comment]
thank you. As a computer science's student this means a lot. :)

**Pull request merged**
